version: 2

sources:
  - name: olist_raw
    database: raw
    tables:
      - name: olist_orders_dataset
      - name: olist_customers_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_products_dataset
      - name: product_category_name_translation