version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: docker/Dockerfile
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__WEBSERVER__SECRET_KEY=your-secret-key-for-webserver
  volumes:
    - ./dags:/usr/local/airflow/dags
    - ./dbt_project:/usr/local/airflow/dbt_project
    - ./data:/usr/local/airflow/data
    - airflow-logs:/usr/local/airflow/logs
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=olist
      - POSTGRES_MULTIPLE_DATABASES=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname Admin --lastname User

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    depends_on:
      - airflow-init

volumes:
  postgres-data:
  airflow-logs: