olist_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres         # This is the service name from docker-compose.yml
      user: postgres
      password: postgres
      port: 5432
      dbname: olist
      schema: marts          # Default schema for dbt models
      threads: 4