olist_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse-server # Docker service name
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER', 'admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'admin') }}"
      schema: intermediate
      threads: 4
      secure: false
