version: 2

sources:
  - name: olist_raw
    database: olist
    schema: raw
    tables:
      - name: olist_orders_dataset
      - name: olist_customers_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset